[2024-10-23T04:33:45.003+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T04:33:45.013+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_data manual__2024-10-23T04:28:30.488605+00:00 [queued]>
[2024-10-23T04:33:45.018+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_data manual__2024-10-23T04:28:30.488605+00:00 [queued]>
[2024-10-23T04:33:45.018+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-23T04:33:45.025+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_data> on 2024-10-23 04:28:30.488605+00:00
[2024-10-23T04:33:45.031+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1672) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-23T04:33:45.032+0000] {standard_task_runner.py:72} INFO - Started process 1674 to run task
[2024-10-23T04:33:45.034+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'insert_data', 'manual__2024-10-23T04:28:30.488605+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpi02094nh']
[2024-10-23T04:33:45.035+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask insert_data
[2024-10-23T04:33:45.061+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_amazon_books.insert_data manual__2024-10-23T04:28:30.488605+00:00 [running]> on host b6ba866339d5
[2024-10-23T04:33:45.106+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T04:28:30.488605+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T04:28:30.488605+00:00'
[2024-10-23T04:33:45.106+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-23T04:33:45.107+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-23T04:33:45.107+0000] {logging_mixin.py:190} INFO - Current task name:insert_data state:running start_date:2024-10-23 04:33:45.013715+00:00
[2024-10-23T04:33:45.107+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books and current dag run status:running
[2024-10-23T04:33:45.107+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T04:33:45.113+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 82, in insert_book_data_into_postgres
    postgres_hook.run(insert_query, parameters=(book['Title'], book['Author'], book['Price'], book['Rating'], book['Description']))
                                                                                              ~~~~^^^^^^^^^^
KeyError: 'Rating'
[2024-10-23T04:33:45.116+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-23T04:33:45.117+0000] {logging_mixin.py:190} INFO - Task start:2024-10-23 04:33:45.013715+00:00 end:2024-10-23 04:33:45.116694+00:00 duration:0.102979
[2024-10-23T04:33:45.117+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-10-23 04:28:30.488605+00:00: manual__2024-10-23T04:28:30.488605+00:00, state:running, queued_at: 2024-10-23 04:28:30.526089+00:00. externally triggered: True>
[2024-10-23T04:33:45.117+0000] {logging_mixin.py:190} INFO - Failure caused by 'Rating'
[2024-10-23T04:33:45.117+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=fetch_and_store_amazon_books, task_id=insert_data, run_id=manual__2024-10-23T04:28:30.488605+00:00, execution_date=20241023T042830, start_date=20241023T043345, end_date=20241023T043345
[2024-10-23T04:33:45.123+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T04:33:45.123+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task insert_data ('Rating'; 1674)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 82, in insert_book_data_into_postgres
    postgres_hook.run(insert_query, parameters=(book['Title'], book['Author'], book['Price'], book['Rating'], book['Description']))
                                                                                              ~~~~^^^^^^^^^^
KeyError: 'Rating'
[2024-10-23T04:33:45.135+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-23T04:33:45.144+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T04:33:45.145+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
